//Program where user has guess a number generated by a program

function guessNumber(){
    //generating a random integer from 1 to 10
    const random = Math.floor(Math.random()*10) = 1;

    //Prompt User for Input
    let number= parseInt(prompt('Guess a number from 1 to 10: '));

    //Accomodate input until guess is correct
    while(number !== random){
        number = parseInt(prompt('Guess a number from 1 to 10 '));
    }
    //Check if number is correct
    if(number === random){
        console.log('Hurray!! You guessed the correct Number!');
    }
}
//Call the function
guessNumber();